### ISSUE TITLE
Finish implementing Maybe

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/true-myth-cs-port#1]
Here's the [reference implementation in TypeScript](https://github.com/chriskrycho/true-myth/blob/master/src/maybe.ts).

Functions and methods to implement:

- [x] unit tests – *all* of them
- `Maybe` static methods
    - [x] `ap` (probably makes sense to name it `Apply`)
    - [x] `equals`
    - [x] `match`
    - [x] `toString`
- `Just` and `Nothing` methods
    - [x] `ap` (probably makes sense to name it `Apply`)
    - [x] `equals`
    - [x] `match`
    - [x] `toString`
- Renames/refactors
    - [x] `Just.IsJust()`, `Nothing.IsNothing()`, corresponding `IMaybe` props -> property, not method
    - [x] `MapOr` -> `SelectOr`
    - [x] `MapOrElse` -> `SelectOrElse`

## Notes

- As noted, the `Just.IsJust()` and `Nothing.IsNothing()` methods should be simple properties, *not* methods. (The reason they were methods in the TS implementation was so they could be used for "type narrowing.")  I *would* keep the `Maybe.IsJust()` and `Maybe.IsNothing()` static methods which are useful for checking them in a "functional" style.
- We probably *don't* need any of the aliases from the original implementation, because they are just there for ease of migration from other JS libraries.
- `ap` is named `ap` instead of `apply` only because `apply` already has a usual meaning in JS. I don't think that's the case here, so using `Apply` makes way more sense to me.

### On curried methods

It's certainly not difficult to supply overloads of the functions for a "functional" style—but it's also not especially idiomatic in C♯ from everything I've seen, so the value proposition seems lower. If folks want it, my thought is we can add them in e.g. a 1.1 release—but I'm happy to help get them shipped if it turns out people *do* really want them!

**Comment by aggieben** [comment]
Closing this in favor of #19.
