### ISSUE TITLE
Move generated docs to gh-pages branch

### ISSUE THREAD

**Issue by aggieben** [chriskrycho/true-myth-cs-port#25]
I think it will be easier to manage automated updates to the docs by committing them on the `gh-pages` branch; it will give us a place to commit changes coming from Azure Pipelines without dirtying up the commit history on actual active branches.

**Comment by aggieben** [comment]
This is done.  There is now an Azure Pipeline build that will tag the sources, create the nuget package, push the documentation, and then publish the Nuget.org package.

**Comment by chriskrycho** [comment]
Huzzah!
