### ISSUE TITLE
Convert documentation from Markdown to XML doc

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/true-myth-cs-port#3]
The implementations have detailed documentation on every single function and method. We should convert this over:

- [x] Convert to XMLDoc
- [x] Convert examples from TypeScript to C♯

**Comment by chrisriesgo** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

**Comment by aggieben** [comment]
This is more-or-less done.  Working now on an automated buildout for github pages.
