### ISSUE TITLE
Set up NuGet package

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/true-myth-cs-port#5]
- [ ] add the package file
- [ ] get the package published/hosted

**Comment by aggieben** [comment]
Package file isn't necessary unless we're doing something that isn't supported by the MSBuild properties in the project file.

The package is currently hosted on nuget.org, latest prerelease is 1.0.0-rc3.
https://www.nuget.org/packages/TrueMyth/1.0.0-rc3
