### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/true-myth-cs-port#6]
Best bet is probably [Appveyor](https://www.appveyor.com), which does free CI and CD for open source projects.

Once we have the integration written, we'll block merges to master on passing tests.

**Comment by chrisriesgo** [comment]
FYI - I set up a quick Appveyor project against my Fork to keep any eye on build status until one is set up against the upstream repo. 

[![Build status](https://ci.appveyor.com/api/projects/status/h0i4nxdciwp9mo5x?svg=true)](https://ci.appveyor.com/project/chrisriesgo/true-myth-csharp)

**Comment by chriskrycho** [comment]
Dang, I forgot that I have to enable it as a maintainer. Can you open a PR with the YAML file, and I’ll flip the switch here to get it integrated?

**Comment by aggieben** [comment]
I've got a working build on myget.org.  Badge:

[![true-myth MyGet Build Status](https://www.myget.org/BuildSource/Badge/true-myth?identifier=cffa15dc-aede-4a2a-926e-8d4d2e4223a3)](https://www.myget.org/)

**Comment by aggieben** [comment]
After difficulty with AppVeyor support, I've started working on this on my own account.  MyGet is sufficient in a pinch (we need a build right now and can't wait until appveyor is straightened out, etc), but i'll eventually get this worked out.

**Comment by aggieben** [comment]
I have this set up on AppVeyor now, although I never really finished.  Badge added to the README.  Will keep working as I can.

**Comment by chriskrycho** [comment]
Solid. Closing accordingly!

**Comment by aggieben** [comment]
I've done this again on Azure Pipelines; it is much more comprehensive (tests against all three supported platforms and both supported framework targets), and more flexible for helping with automating releases, is triggered to verify PRs, etc.

https://dev.azure.com/true-myth/TrueMyth/_build?definitionId=1&_a=summary

CI builds get pushed here: https://www.myget.org/feed/true-myth/package/nuget/TrueMyth.  They only build on changes to `master`; builds triggered by PRs do not create CI artifacts.
