### ISSUE TITLE
Put all "unsafe" operations into a separate ".Unsafe" namespace

### ISSUE THREAD

**Issue by chrisriesgo** [chriskrycho/true-myth-cs-port#8]
Idea: label this as "Proposal" or similar?

**Example:**
```csharp
namespace TrueMyth.Unsafe
{
    public static class UnsafeExtensions
    {
        public static TValue Value(this IMaybe<TValue> maybeValue) { ... }
    }
}
```

**Comment by chrisriesgo** [comment]
To be perfectly honest, there may not be any of these in the library. Should know more after the Maybe + Result implementations are done. :-)

**Comment by chriskrycho** [comment]
There are a few, e.g. `UnsafelyUnwrap`, and it's a good idea to split them out this way.
